vich_uploader:
    db_driver: orm

    mappings:
        category_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logo_site:
            uri_prefix: /uploads/logo_site
            upload_destination: '%kernel.project_dir%/public/uploads/logo_site/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        menu_image:
            uri_prefix: /uploads/menu_image
            upload_destination: '%kernel.project_dir%/public/uploads/menu_image/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        slider_image:
            uri_prefix: /uploads/slider_image
            upload_destination: '%kernel.project_dir%/public/uploads/slider_image/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
